# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Sentius Docs
site_url: https://docs.sentius.ai/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
  palette:
    scheme: slate
    primary: light blue

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - Platform Components: 
    - Overview: platform-components.md
    - Agents: 
      - Overview: platform-components/agents.md
      - Browser Agent: platform-components/agents/browser-agent.md
      - OpenAPI Agent: platform-components/agents/openapi-agent.md
      - Prompt Agent: platform-components/agents/prompt-agent.md
    - Services:
      - Workflow Engine: platform-components/services/workflow-engine.md
    - Applications: 
      - Sentius Copilot+: platform-components/applications/sentius-copilot-plus.md
      - Sentius Studio: platform-components/applications/sentius-studio.md
  - API Usage:
    - api/index.md
    - Dialog Sessions: api/dialog-sessions.md
    - Tasks and instructions: api/tasks.md
